/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NftContract } from "./NftContract";

export { NftContract__factory } from "./factories/NftContract__factory";
